var str = "This is string type.";
var bool = true;
var x;
var value = null; 
var y = 11.2;
console.log(typeof str);
console.log(typeof bool);
console.log(typeof x);
console.log(typeof value);
console.log(typeof y);